export const userData = {
  originally_created: '',
  id: '',
  ip_address: '',
  trusted_form_cert_url: '',
  user_agent: '',
  first_name: '',
  last_name: '',
  email: '',
  phone: '',
  address: '',
  city: '',
  state: '',
  zip_code: '',
  birth_date: '',
  gender: '',
  marital_status: '',
  property_type: '',
  property_size: '',
  claims: '',
  credit: '',
  ownership: '',
  occupancy: '',
  year_built: '',
  insurance_company: '',
  expiration_date: '',
}